### PR TITLE
Convert Publish Dates

### LINKED ISSUE #71: Update Publish Dates
**Is your feature request related to a problem? Please describe.**
Publish dates are currently in a weir format. 

**Describe the solution you'd like**
Reformat them to make them easier to understand

### PR DESCRIPTION
**Pull request by krferrell**
## Changes
1. Reformat dates to be easier to read

## Purpose
Enhance UX

## Approach
Moved a function to a utils folder and imported it everywhere it was needed. 

Closes #71

### CODE REVIEW

**Review by Lap343 — APPROVED** [review]
Nice job. Code looks good

**Review by connielion — APPROVED** [review]
Looks noice!

**Review by kmausolf — COMMENTED** [review]
I'd suggest checking out Moment.js for datetime formatting, but this looks good!

**Review by JorgeLVilla — APPROVED** [review]
Nice job!

**Comment by krferrell** [comment]
> I'd suggest checking out Moment.js for datetime formatting, but this looks good!

Thanks for the Info! I will check it out next time!

**Pull request merged**
