### PR TITLE
Refactor Modules File

### LINKED ISSUE #45: Refactor Modules File
**Is your feature request related to a problem? Please describe.**
Cannot import and export interfaces in the ts module

**Describe the solution you'd like**
Make the ts a js file and more the interfaces to the js file

### PR DESCRIPTION
**Pull request by BlackCubes**
## Changes
1. Exported the type interfaces into a `type export` to be used everywhere in the app.
2. Changed some of the interfaces names to better match the interface.
3. Changed some of the imports for the interfaces that the components used.

## Purpose
There needs to be a way for the interfaces in the `api` files to be exported in `api/index.ts` so it could be used everywhere.

## Approach
In order to let the interfaces be exported in `api/index.ts`, it needs to be separated from the normal `export` into its own such as: `export type { }`. The `export type` provides an export that can be used for type contexts, and is also erased from TypeScript’s output.

Then, the interfaces could be reused everywhere in the app by using `import type {  } from api/index` where `import type` only imports declarations to be used for type annotations and declarations.

The names of the interfaces were also changed to better reflect that it is an interface.

Overall, this creates a clean code for the developers to use. 

## Learning
[TypeScript: Documentation - Modules](https://www.typescriptlang.org/docs/handbook/modules.html)

[Type-Only Imports and Export](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html)

Closes #45

### CODE REVIEW

**Review by connielion — APPROVED** [review]
Looks great!

**Review by Lap343 — APPROVED** [review]
Damn this looks like one huge headache of a PR. Hats off to you guys for figuring it out

**Review by gonzalespaulb — APPROVED** [review]

**Review by Gjhnsn — APPROVED** [review]
so clean and organized, great job!

**Review by JorgeLVilla — APPROVED** [review]
Definitely learned a lot from this one. Nice job on keeping it organized as well.

**Pull request merged**
