### PR TITLE
Details Page Responsive

### LINKED ISSUE #103: Fix Details-Page Responsive
## Expected Behavior
The DetailsPage should be responsive.

## Actual/Current Behavior
It is not responsive.

### PR DESCRIPTION
**Pull request by JayDampitan**
## Changes
1. Fix More Info responsive designs at different break points. 

## Purpose
More Info Page should be responsible on all break points. 

Closes #103

### CODE REVIEW

**Review by connielion — APPROVED** [review]
Nice!

**Review by Lap343 — APPROVED** [review]
Code looks good

**Review by Gjhnsn — APPROVED** [review]
Looks gooooood

**Review by gonzalespaulb — APPROVED** [review]
Can't wait to see how the final product looks

**Pull request merged**
